server:
  port: 8080
  servlet:
    context-path: /

spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/var/h2/spring-boot-h2-db
    username: sa
    password: